package require -exact qsys 15.0
set_module_property NAME average_value_internal
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property GROUP HLS
set_module_property DISPLAY_NAME average_value_internal
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_assignment hls.cosim.name {average_value}

#### Synthesis fileset
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL average_value_internal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dspba_library_package.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library_package.vhd
add_fileset_file dspba_library.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library.vhd
add_fileset_file acl_data_fifo.v SYSTEM_VERILOG PATH ip/acl_data_fifo.v
add_fileset_file acl_fifo.v SYSTEM_VERILOG PATH ip/acl_fifo.v
add_fileset_file acl_ll_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_fifo.v
add_fileset_file acl_ll_ram_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_ram_fifo.v
add_fileset_file acl_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_valid_fifo_counter.v
add_fileset_file acl_dspba_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_dspba_valid_fifo_counter.v
add_fileset_file acl_staging_reg.v SYSTEM_VERILOG PATH ip/acl_staging_reg.v
add_fileset_file hld_fifo.sv SYSTEM_VERILOG PATH ip/hld_fifo.sv
add_fileset_file hld_fifo_zero_width.sv SYSTEM_VERILOG PATH ip/hld_fifo_zero_width.sv
add_fileset_file acl_high_speed_fifo.sv SYSTEM_VERILOG PATH ip/acl_high_speed_fifo.sv
add_fileset_file acl_low_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_low_latency_fifo.sv
add_fileset_file acl_zero_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_zero_latency_fifo.sv
add_fileset_file acl_fanout_pipeline.sv SYSTEM_VERILOG PATH ip/acl_fanout_pipeline.sv
add_fileset_file acl_std_synchronizer_nocut.v SYSTEM_VERILOG PATH ip/acl_std_synchronizer_nocut.v
add_fileset_file acl_tessellated_incr_decr_threshold.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_decr_threshold.sv
add_fileset_file acl_tessellated_incr_lookahead.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_lookahead.sv
add_fileset_file acl_reset_handler.sv SYSTEM_VERILOG PATH ip/acl_reset_handler.sv
add_fileset_file acl_lfsr.sv SYSTEM_VERILOG PATH ip/acl_lfsr.sv
add_fileset_file acl_pop.v SYSTEM_VERILOG PATH ip/acl_pop.v
add_fileset_file acl_push.v SYSTEM_VERILOG PATH ip/acl_push.v
add_fileset_file acl_token_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_token_fifo_counter.v
add_fileset_file acl_pipeline.v SYSTEM_VERILOG PATH ip/acl_pipeline.v
add_fileset_file acl_dspba_buffer.v SYSTEM_VERILOG PATH ip/acl_dspba_buffer.v
add_fileset_file acl_enable_sink.v SYSTEM_VERILOG PATH ip/acl_enable_sink.v
add_fileset_file st_top.v SYSTEM_VERILOG PATH ip/st_top.v
add_fileset_file lsu_top.v SYSTEM_VERILOG PATH ip/lsu_top.v
add_fileset_file lsu_permute_address.v SYSTEM_VERILOG PATH ip/lsu_permute_address.v
add_fileset_file lsu_pipelined.v SYSTEM_VERILOG PATH ip/lsu_pipelined.v
add_fileset_file lsu_enabled.v SYSTEM_VERILOG PATH ip/lsu_enabled.v
add_fileset_file lsu_basic_coalescer.v SYSTEM_VERILOG PATH ip/lsu_basic_coalescer.v
add_fileset_file lsu_simple.v SYSTEM_VERILOG PATH ip/lsu_simple.v
add_fileset_file lsu_streaming.v SYSTEM_VERILOG PATH ip/lsu_streaming.v
add_fileset_file lsu_burst_master.v SYSTEM_VERILOG PATH ip/lsu_burst_master.v
add_fileset_file lsu_bursting_load_stores.v SYSTEM_VERILOG PATH ip/lsu_bursting_load_stores.v
add_fileset_file lsu_non_aligned_write.v SYSTEM_VERILOG PATH ip/lsu_non_aligned_write.v
add_fileset_file lsu_read_cache.v SYSTEM_VERILOG PATH ip/lsu_read_cache.v
add_fileset_file lsu_atomic.v SYSTEM_VERILOG PATH ip/lsu_atomic.v
add_fileset_file lsu_prefetch_block.v SYSTEM_VERILOG PATH ip/lsu_prefetch_block.v
add_fileset_file lsu_wide_wrapper.v SYSTEM_VERILOG PATH ip/lsu_wide_wrapper.v
add_fileset_file lsu_streaming_prefetch.v SYSTEM_VERILOG PATH ip/lsu_streaming_prefetch.v
add_fileset_file acl_aligned_burst_coalesced_lsu.v SYSTEM_VERILOG PATH ip/acl_aligned_burst_coalesced_lsu.v
add_fileset_file acl_toggle_detect.v SYSTEM_VERILOG PATH ip/acl_toggle_detect.v
add_fileset_file acl_debug_mem.v SYSTEM_VERILOG PATH ip/acl_debug_mem.v
add_fileset_file lsu_burst_coalesced_pipelined_write.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_write.sv
add_fileset_file lsu_burst_coalesced_pipelined_read.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_read.sv
add_fileset_file acl_fifo_stall_valid_lookahead.sv SYSTEM_VERILOG PATH ip/acl_fifo_stall_valid_lookahead.sv
add_fileset_file acl_ffwdsrc.v SYSTEM_VERILOG PATH ip/acl_ffwdsrc.v
add_fileset_file acl_full_detector.v SYSTEM_VERILOG PATH ip/acl_full_detector.v
add_fileset_file ternary_add.v SYSTEM_VERILOG PATH ip/ternary_add.v
add_fileset_file six_three_comp.v SYSTEM_VERILOG PATH ip/six_three_comp.v
add_fileset_file thirtysix_six_comp.v SYSTEM_VERILOG PATH ip/thirtysix_six_comp.v
add_fileset_file acl_loop_limiter.v SYSTEM_VERILOG PATH ip/acl_loop_limiter.v
add_fileset_file acl_reset_wire.v SYSTEM_VERILOG PATH ip/acl_reset_wire.v
add_fileset_file average_value_function_wrapper.vhd VHDL PATH ip/average_value_function_wrapper.vhd
add_fileset_file average_value_function.vhd VHDL PATH ip/average_value_function.vhd
add_fileset_file bb_average_value_B2_sr_1.vhd VHDL PATH ip/bb_average_value_B2_sr_1.vhd
add_fileset_file bb_average_value_B3_sr_0.vhd VHDL PATH ip/bb_average_value_B3_sr_0.vhd
add_fileset_file bb_average_value_B0_runOnce.vhd VHDL PATH ip/bb_average_value_B0_runOnce.vhd
add_fileset_file average_value_B0_runOnce_branch.vhd VHDL PATH ip/average_value_B0_runOnce_branch.vhd
add_fileset_file average_value_B0_runOnce_merge.vhd VHDL PATH ip/average_value_B0_runOnce_merge.vhd
add_fileset_file bb_average_value_B0_runOnce_stall_region.vhd VHDL PATH ip/bb_average_value_B0_runOnce_stall_region.vhd
add_fileset_file average_value_B0_runOnce_merge_reg.vhd VHDL PATH ip/average_value_B0_runOnce_merge_reg.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_average_value0.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_average_value0.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_average_value_reg.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_average_value_reg.vhd
add_fileset_file i_acl_push_i1_wt_limpush_average_value2.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_average_value2.vhd
add_fileset_file i_acl_push_i1_wt_limpush_average_value_reg.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_average_value_reg.vhd
add_fileset_file bb_average_value_B1_start.vhd VHDL PATH ip/bb_average_value_B1_start.vhd
add_fileset_file average_value_B1_start_branch.vhd VHDL PATH ip/average_value_B1_start_branch.vhd
add_fileset_file average_value_B1_start_merge.vhd VHDL PATH ip/average_value_B1_start_merge.vhd
add_fileset_file bb_average_value_B1_start_stall_region.vhd VHDL PATH ip/bb_average_value_B1_start_stall_region.vhd
add_fileset_file i_sfc_c0_wt_entry_average_value_c0_enter_average_value.vhd VHDL PATH ip/i_sfc_c0_wt_entry_average_value_c0_enter_average_value.vhd
add_fileset_file i_acl_sfc_exit_c0_wt_entry_average_valueA0Z_average_value10.vhd VHDL PATH ip/i_acl_sfc_exit_c0_wt_entry_average_valueA0Z_average_value10.vhd
add_fileset_file i_sfc_logic_c0_wt_entry_average_value_c0A0Zr_average_value4.vhd VHDL PATH ip/i_sfc_logic_c0_wt_entry_average_value_c0A0Zr_average_value4.vhd
add_fileset_file i_acl_pipeline_keep_going9_average_value6.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_average_value6.vhd
add_fileset_file i_acl_push_i1_notexitcond10_average_value8.vhd VHDL PATH ip/i_acl_push_i1_notexitcond10_average_value8.vhd
add_fileset_file average_value_B1_start_merge_reg.vhd VHDL PATH ip/average_value_B1_start_merge_reg.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_average_value12.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_average_value12.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_average_value_reg.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_average_value_reg.vhd
add_fileset_file i_iord_bl_do_unnamed_average_value1_average_value14.vhd VHDL PATH ip/i_iord_bl_do_unnamed_average_value1_average_value14.vhd
add_fileset_file bb_average_value_B2.vhd VHDL PATH ip/bb_average_value_B2.vhd
add_fileset_file average_value_B2_branch.vhd VHDL PATH ip/average_value_B2_branch.vhd
add_fileset_file average_value_B2_merge.vhd VHDL PATH ip/average_value_B2_merge.vhd
add_fileset_file bb_average_value_B2_stall_region.vhd VHDL PATH ip/bb_average_value_B2_stall_region.vhd
add_fileset_file average_value_B2_merge_reg.vhd VHDL PATH ip/average_value_B2_merge_reg.vhd
add_fileset_file i_sfc_c0_0_ac_fixed_0ca_0ba_0_0_0_qeaa_mA0Z12_average_value.vhd VHDL PATH ip/i_sfc_c0_0_ac_fixed_0ca_0ba_0_0_0_qeaa_mA0Z12_average_value.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Z_average_value66.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Z_average_value66.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Zlue137_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Zlue137_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Zue_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Zue_full_detector.vhd
add_fileset_file i_sfc_logic_c0_0_ac_fixed_0ca_0ba_0_0_0_A0Z_average_value15.vhd VHDL PATH ip/i_sfc_logic_c0_0_ac_fixed_0ca_0ba_0_0_0_A0Z_average_value15.vhd
add_fileset_file i_acl_pipeline_keep_going_average_value21.vhd VHDL PATH ip/i_acl_pipeline_keep_going_average_value21.vhd
add_fileset_file i_acl_pop_i32_i_039_pop6_average_value32.vhd VHDL PATH ip/i_acl_pop_i32_i_039_pop6_average_value32.vhd
add_fileset_file i_acl_pop_i4_cleanups_pop9_average_value17.vhd VHDL PATH ip/i_acl_pop_i4_cleanups_pop9_average_value17.vhd
add_fileset_file i_acl_pop_i4_initerations_pop8_average_value23.vhd VHDL PATH ip/i_acl_pop_i4_initerations_pop8_average_value23.vhd
add_fileset_file i_acl_pop_i64_temp_0_0_038_pop7_average_value47.vhd VHDL PATH ip/i_acl_pop_i64_temp_0_0_038_pop7_average_value47.vhd
add_fileset_file i_acl_push_i1_lastiniteration_average_value30.vhd VHDL PATH ip/i_acl_push_i1_lastiniteration_average_value30.vhd
add_fileset_file i_acl_push_i1_notexitcond_average_value57.vhd VHDL PATH ip/i_acl_push_i1_notexitcond_average_value57.vhd
add_fileset_file i_acl_push_i32_i_039_push6_average_value51.vhd VHDL PATH ip/i_acl_push_i32_i_039_push6_average_value51.vhd
add_fileset_file i_acl_push_i4_cleanups_push9_average_value60.vhd VHDL PATH ip/i_acl_push_i4_cleanups_push9_average_value60.vhd
add_fileset_file i_acl_push_i4_initerations_push8_average_value26.vhd VHDL PATH ip/i_acl_push_i4_initerations_push8_average_value26.vhd
add_fileset_file i_acl_push_i64_temp_0_0_038_push7_average_value49.vhd VHDL PATH ip/i_acl_push_i64_temp_0_0_038_push7_average_value49.vhd
add_fileset_file i_ffwd_src_unnamed_average_value3_average_value62.vhd VHDL PATH ip/i_ffwd_src_unnamed_average_value3_average_value62.vhd
add_fileset_file i_ffwd_src_unnamed_average_value4_average_value64.vhd VHDL PATH ip/i_ffwd_src_unnamed_average_value4_average_value64.vhd
add_fileset_file i_load_unnamed_average_value2_average_value40.vhd VHDL PATH ip/i_load_unnamed_average_value2_average_value40.vhd
add_fileset_file i_syncbuf_a_sync_buffer_average_value34.vhd VHDL PATH ip/i_syncbuf_a_sync_buffer_average_value34.vhd
add_fileset_file i_syncbuf_n_sync_buffer4_average_value53.vhd VHDL PATH ip/i_syncbuf_n_sync_buffer4_average_value53.vhd
add_fileset_file i_syncbuf_n_sync_buffer_average_value37.vhd VHDL PATH ip/i_syncbuf_n_sync_buffer_average_value37.vhd
add_fileset_file bb_average_value_B3.vhd VHDL PATH ip/bb_average_value_B3.vhd
add_fileset_file average_value_B3_branch.vhd VHDL PATH ip/average_value_B3_branch.vhd
add_fileset_file average_value_B3_merge.vhd VHDL PATH ip/average_value_B3_merge.vhd
add_fileset_file bb_average_value_B3_stall_region.vhd VHDL PATH ip/bb_average_value_B3_stall_region.vhd
add_fileset_file i_sfc_c0_for_cond_for_end_crit_edge_loopA0Z16_average_value.vhd VHDL PATH ip/i_sfc_c0_for_cond_for_end_crit_edge_loopA0Z16_average_value.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zaverage_value133.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zaverage_value133.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zlue139_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zlue139_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zue_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zue_full_detector.vhd
add_fileset_file i_sfc_logic_c0_for_cond_for_end_crit_edgA0Z_average_value67.vhd VHDL PATH ip/i_sfc_logic_c0_for_cond_for_end_crit_edgA0Z_average_value67.vhd
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA0Z463a0054c2a6355y.vhd VHDL PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA0Z463a0054c2a6355y.vhd
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA0Z0j0ucqp00j0oqf0z.vhd VHDL PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA0Z0j0ucqp00j0oqf0z.vhd
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA0ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA0ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA1ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA1ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA2ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA2ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA3ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA3ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA4ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA4ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA5ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA5ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA6ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA6ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA7ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA7ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA8ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA8ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA9ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA9ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA10ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA10ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA11ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA11ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA12ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA12ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA13ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA13ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA14ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA14ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA15ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA15ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA16ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA16ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA17ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA17ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA18ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA18ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA19ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA19ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA20ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA20ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA21ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA21ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA22ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA22ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA23ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA23ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA24ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA24ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA25ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA25ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA26ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA26ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA27ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA27ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA28ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA28ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA29ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA29ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA30ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA30ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA31ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA31ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA32ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA32ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA33ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA33ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA34ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA34ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA35ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA35ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA36ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA36ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA37ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA37ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA38ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA38ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA39ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA39ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA40ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA40ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA41ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA41ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA42ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA42ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA43ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA43ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA44ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA44ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA45ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA45ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA46ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA46ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA47ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA47ZinvTables_lutmem.hex
add_fileset_file i_ffwd_dst_conv_i_i_i_i6_average_value71.vhd VHDL PATH ip/i_ffwd_dst_conv_i_i_i_i6_average_value71.vhd
add_fileset_file i_ffwd_dst_temp_0_0_0385_average_value69.vhd VHDL PATH ip/i_ffwd_dst_temp_0_0_0385_average_value69.vhd
add_fileset_file i_syncbuf_n_sync_buffer2_average_value73.vhd VHDL PATH ip/i_syncbuf_n_sync_buffer2_average_value73.vhd
add_fileset_file i_syncbuf_n_sync_buffer3_average_value116.vhd VHDL PATH ip/i_syncbuf_n_sync_buffer3_average_value116.vhd
add_fileset_file i_acl_push_i1_throttle_push_average_value135.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_average_value135.vhd
add_fileset_file i_acl_push_i1_throttle_push_average_value_reg.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_average_value_reg.vhd
add_fileset_file i_iowr_nb_return_unnamed_average_value8_A0Zaverage_value134.vhd VHDL PATH ip/i_iowr_nb_return_unnamed_average_value8_A0Zaverage_value134.vhd
add_fileset_file i_acl_pipeline_keep_going9_average_value_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_average_value_sr.vhd
add_fileset_file i_acl_pipeline_keep_going9_average_value_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_average_value_valid_fifo.vhd
add_fileset_file i_acl_pipeline_keep_going_average_value_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going_average_value_sr.vhd
add_fileset_file i_acl_pipeline_keep_going_average_value_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going_average_value_valid_fifo.vhd
add_fileset_file loop_limiter_average_value0.vhd VHDL PATH ip/loop_limiter_average_value0.vhd
add_fileset_file acl_avm_to_ic.v SYSTEM_VERILOG PATH ip/acl_avm_to_ic.v
add_fileset_file acl_mem1x.v SYSTEM_VERILOG PATH ip/acl_mem1x.v
add_fileset_file acl_mem_staging_reg.v SYSTEM_VERILOG PATH ip/acl_mem_staging_reg.v
add_fileset_file acl_ic_local_mem_router.v SYSTEM_VERILOG PATH ip/acl_ic_local_mem_router.v
add_fileset_file acl_ic_master_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_master_endpoint.v
add_fileset_file acl_arb_intf.v SYSTEM_VERILOG PATH ip/acl_arb_intf.v
add_fileset_file acl_ic_intf.v SYSTEM_VERILOG PATH ip/acl_ic_intf.v
add_fileset_file acl_ic_slave_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_slave_endpoint.v
add_fileset_file acl_ic_slave_rrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_rrp.v
add_fileset_file acl_ic_slave_wrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_wrp.v
add_fileset_file average_value_internal.v SYSTEM_VERILOG PATH average_value_internal.v

#### Simulation fileset
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL average_value_internal
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dspba_library_package.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library_package.vhd
add_fileset_file dspba_library.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library.vhd
add_fileset_file acl_data_fifo.v SYSTEM_VERILOG PATH ip/acl_data_fifo.v
add_fileset_file acl_fifo.v SYSTEM_VERILOG PATH ip/acl_fifo.v
add_fileset_file acl_ll_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_fifo.v
add_fileset_file acl_ll_ram_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_ram_fifo.v
add_fileset_file acl_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_valid_fifo_counter.v
add_fileset_file acl_dspba_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_dspba_valid_fifo_counter.v
add_fileset_file acl_staging_reg.v SYSTEM_VERILOG PATH ip/acl_staging_reg.v
add_fileset_file hld_fifo.sv SYSTEM_VERILOG PATH ip/hld_fifo.sv
add_fileset_file hld_fifo_zero_width.sv SYSTEM_VERILOG PATH ip/hld_fifo_zero_width.sv
add_fileset_file acl_high_speed_fifo.sv SYSTEM_VERILOG PATH ip/acl_high_speed_fifo.sv
add_fileset_file acl_low_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_low_latency_fifo.sv
add_fileset_file acl_zero_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_zero_latency_fifo.sv
add_fileset_file acl_fanout_pipeline.sv SYSTEM_VERILOG PATH ip/acl_fanout_pipeline.sv
add_fileset_file acl_std_synchronizer_nocut.v SYSTEM_VERILOG PATH ip/acl_std_synchronizer_nocut.v
add_fileset_file acl_tessellated_incr_decr_threshold.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_decr_threshold.sv
add_fileset_file acl_tessellated_incr_lookahead.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_lookahead.sv
add_fileset_file acl_reset_handler.sv SYSTEM_VERILOG PATH ip/acl_reset_handler.sv
add_fileset_file acl_lfsr.sv SYSTEM_VERILOG PATH ip/acl_lfsr.sv
add_fileset_file acl_pop.v SYSTEM_VERILOG PATH ip/acl_pop.v
add_fileset_file acl_push.v SYSTEM_VERILOG PATH ip/acl_push.v
add_fileset_file acl_token_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_token_fifo_counter.v
add_fileset_file acl_pipeline.v SYSTEM_VERILOG PATH ip/acl_pipeline.v
add_fileset_file acl_dspba_buffer.v SYSTEM_VERILOG PATH ip/acl_dspba_buffer.v
add_fileset_file acl_enable_sink.v SYSTEM_VERILOG PATH ip/acl_enable_sink.v
add_fileset_file st_top.v SYSTEM_VERILOG PATH ip/st_top.v
add_fileset_file lsu_top.v SYSTEM_VERILOG PATH ip/lsu_top.v
add_fileset_file lsu_permute_address.v SYSTEM_VERILOG PATH ip/lsu_permute_address.v
add_fileset_file lsu_pipelined.v SYSTEM_VERILOG PATH ip/lsu_pipelined.v
add_fileset_file lsu_enabled.v SYSTEM_VERILOG PATH ip/lsu_enabled.v
add_fileset_file lsu_basic_coalescer.v SYSTEM_VERILOG PATH ip/lsu_basic_coalescer.v
add_fileset_file lsu_simple.v SYSTEM_VERILOG PATH ip/lsu_simple.v
add_fileset_file lsu_streaming.v SYSTEM_VERILOG PATH ip/lsu_streaming.v
add_fileset_file lsu_burst_master.v SYSTEM_VERILOG PATH ip/lsu_burst_master.v
add_fileset_file lsu_bursting_load_stores.v SYSTEM_VERILOG PATH ip/lsu_bursting_load_stores.v
add_fileset_file lsu_non_aligned_write.v SYSTEM_VERILOG PATH ip/lsu_non_aligned_write.v
add_fileset_file lsu_read_cache.v SYSTEM_VERILOG PATH ip/lsu_read_cache.v
add_fileset_file lsu_atomic.v SYSTEM_VERILOG PATH ip/lsu_atomic.v
add_fileset_file lsu_prefetch_block.v SYSTEM_VERILOG PATH ip/lsu_prefetch_block.v
add_fileset_file lsu_wide_wrapper.v SYSTEM_VERILOG PATH ip/lsu_wide_wrapper.v
add_fileset_file lsu_streaming_prefetch.v SYSTEM_VERILOG PATH ip/lsu_streaming_prefetch.v
add_fileset_file acl_aligned_burst_coalesced_lsu.v SYSTEM_VERILOG PATH ip/acl_aligned_burst_coalesced_lsu.v
add_fileset_file acl_toggle_detect.v SYSTEM_VERILOG PATH ip/acl_toggle_detect.v
add_fileset_file acl_debug_mem.v SYSTEM_VERILOG PATH ip/acl_debug_mem.v
add_fileset_file lsu_burst_coalesced_pipelined_write.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_write.sv
add_fileset_file lsu_burst_coalesced_pipelined_read.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_read.sv
add_fileset_file acl_fifo_stall_valid_lookahead.sv SYSTEM_VERILOG PATH ip/acl_fifo_stall_valid_lookahead.sv
add_fileset_file acl_ffwdsrc.v SYSTEM_VERILOG PATH ip/acl_ffwdsrc.v
add_fileset_file acl_full_detector.v SYSTEM_VERILOG PATH ip/acl_full_detector.v
add_fileset_file ternary_add.v SYSTEM_VERILOG PATH ip/ternary_add.v
add_fileset_file six_three_comp.v SYSTEM_VERILOG PATH ip/six_three_comp.v
add_fileset_file thirtysix_six_comp.v SYSTEM_VERILOG PATH ip/thirtysix_six_comp.v
add_fileset_file acl_loop_limiter.v SYSTEM_VERILOG PATH ip/acl_loop_limiter.v
add_fileset_file acl_reset_wire.v SYSTEM_VERILOG PATH ip/acl_reset_wire.v
add_fileset_file average_value_function_wrapper.vhd VHDL PATH ip/average_value_function_wrapper.vhd
add_fileset_file average_value_function.vhd VHDL PATH ip/average_value_function.vhd
add_fileset_file bb_average_value_B2_sr_1.vhd VHDL PATH ip/bb_average_value_B2_sr_1.vhd
add_fileset_file bb_average_value_B3_sr_0.vhd VHDL PATH ip/bb_average_value_B3_sr_0.vhd
add_fileset_file bb_average_value_B0_runOnce.vhd VHDL PATH ip/bb_average_value_B0_runOnce.vhd
add_fileset_file average_value_B0_runOnce_branch.vhd VHDL PATH ip/average_value_B0_runOnce_branch.vhd
add_fileset_file average_value_B0_runOnce_merge.vhd VHDL PATH ip/average_value_B0_runOnce_merge.vhd
add_fileset_file bb_average_value_B0_runOnce_stall_region.vhd VHDL PATH ip/bb_average_value_B0_runOnce_stall_region.vhd
add_fileset_file average_value_B0_runOnce_merge_reg.vhd VHDL PATH ip/average_value_B0_runOnce_merge_reg.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_average_value0.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_average_value0.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_average_value_reg.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_average_value_reg.vhd
add_fileset_file i_acl_push_i1_wt_limpush_average_value2.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_average_value2.vhd
add_fileset_file i_acl_push_i1_wt_limpush_average_value_reg.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_average_value_reg.vhd
add_fileset_file bb_average_value_B1_start.vhd VHDL PATH ip/bb_average_value_B1_start.vhd
add_fileset_file average_value_B1_start_branch.vhd VHDL PATH ip/average_value_B1_start_branch.vhd
add_fileset_file average_value_B1_start_merge.vhd VHDL PATH ip/average_value_B1_start_merge.vhd
add_fileset_file bb_average_value_B1_start_stall_region.vhd VHDL PATH ip/bb_average_value_B1_start_stall_region.vhd
add_fileset_file i_sfc_c0_wt_entry_average_value_c0_enter_average_value.vhd VHDL PATH ip/i_sfc_c0_wt_entry_average_value_c0_enter_average_value.vhd
add_fileset_file i_acl_sfc_exit_c0_wt_entry_average_valueA0Z_average_value10.vhd VHDL PATH ip/i_acl_sfc_exit_c0_wt_entry_average_valueA0Z_average_value10.vhd
add_fileset_file i_sfc_logic_c0_wt_entry_average_value_c0A0Zr_average_value4.vhd VHDL PATH ip/i_sfc_logic_c0_wt_entry_average_value_c0A0Zr_average_value4.vhd
add_fileset_file i_acl_pipeline_keep_going9_average_value6.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_average_value6.vhd
add_fileset_file i_acl_push_i1_notexitcond10_average_value8.vhd VHDL PATH ip/i_acl_push_i1_notexitcond10_average_value8.vhd
add_fileset_file average_value_B1_start_merge_reg.vhd VHDL PATH ip/average_value_B1_start_merge_reg.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_average_value12.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_average_value12.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_average_value_reg.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_average_value_reg.vhd
add_fileset_file i_iord_bl_do_unnamed_average_value1_average_value14.vhd VHDL PATH ip/i_iord_bl_do_unnamed_average_value1_average_value14.vhd
add_fileset_file bb_average_value_B2.vhd VHDL PATH ip/bb_average_value_B2.vhd
add_fileset_file average_value_B2_branch.vhd VHDL PATH ip/average_value_B2_branch.vhd
add_fileset_file average_value_B2_merge.vhd VHDL PATH ip/average_value_B2_merge.vhd
add_fileset_file bb_average_value_B2_stall_region.vhd VHDL PATH ip/bb_average_value_B2_stall_region.vhd
add_fileset_file average_value_B2_merge_reg.vhd VHDL PATH ip/average_value_B2_merge_reg.vhd
add_fileset_file i_sfc_c0_0_ac_fixed_0ca_0ba_0_0_0_qeaa_mA0Z12_average_value.vhd VHDL PATH ip/i_sfc_c0_0_ac_fixed_0ca_0ba_0_0_0_qeaa_mA0Z12_average_value.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Z_average_value66.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Z_average_value66.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Zlue137_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Zlue137_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Zue_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ca_0ba_0_0A0Zue_full_detector.vhd
add_fileset_file i_sfc_logic_c0_0_ac_fixed_0ca_0ba_0_0_0_A0Z_average_value15.vhd VHDL PATH ip/i_sfc_logic_c0_0_ac_fixed_0ca_0ba_0_0_0_A0Z_average_value15.vhd
add_fileset_file i_acl_pipeline_keep_going_average_value21.vhd VHDL PATH ip/i_acl_pipeline_keep_going_average_value21.vhd
add_fileset_file i_acl_pop_i32_i_039_pop6_average_value32.vhd VHDL PATH ip/i_acl_pop_i32_i_039_pop6_average_value32.vhd
add_fileset_file i_acl_pop_i4_cleanups_pop9_average_value17.vhd VHDL PATH ip/i_acl_pop_i4_cleanups_pop9_average_value17.vhd
add_fileset_file i_acl_pop_i4_initerations_pop8_average_value23.vhd VHDL PATH ip/i_acl_pop_i4_initerations_pop8_average_value23.vhd
add_fileset_file i_acl_pop_i64_temp_0_0_038_pop7_average_value47.vhd VHDL PATH ip/i_acl_pop_i64_temp_0_0_038_pop7_average_value47.vhd
add_fileset_file i_acl_push_i1_lastiniteration_average_value30.vhd VHDL PATH ip/i_acl_push_i1_lastiniteration_average_value30.vhd
add_fileset_file i_acl_push_i1_notexitcond_average_value57.vhd VHDL PATH ip/i_acl_push_i1_notexitcond_average_value57.vhd
add_fileset_file i_acl_push_i32_i_039_push6_average_value51.vhd VHDL PATH ip/i_acl_push_i32_i_039_push6_average_value51.vhd
add_fileset_file i_acl_push_i4_cleanups_push9_average_value60.vhd VHDL PATH ip/i_acl_push_i4_cleanups_push9_average_value60.vhd
add_fileset_file i_acl_push_i4_initerations_push8_average_value26.vhd VHDL PATH ip/i_acl_push_i4_initerations_push8_average_value26.vhd
add_fileset_file i_acl_push_i64_temp_0_0_038_push7_average_value49.vhd VHDL PATH ip/i_acl_push_i64_temp_0_0_038_push7_average_value49.vhd
add_fileset_file i_ffwd_src_unnamed_average_value3_average_value62.vhd VHDL PATH ip/i_ffwd_src_unnamed_average_value3_average_value62.vhd
add_fileset_file i_ffwd_src_unnamed_average_value4_average_value64.vhd VHDL PATH ip/i_ffwd_src_unnamed_average_value4_average_value64.vhd
add_fileset_file i_load_unnamed_average_value2_average_value40.vhd VHDL PATH ip/i_load_unnamed_average_value2_average_value40.vhd
add_fileset_file i_syncbuf_a_sync_buffer_average_value34.vhd VHDL PATH ip/i_syncbuf_a_sync_buffer_average_value34.vhd
add_fileset_file i_syncbuf_n_sync_buffer4_average_value53.vhd VHDL PATH ip/i_syncbuf_n_sync_buffer4_average_value53.vhd
add_fileset_file i_syncbuf_n_sync_buffer_average_value37.vhd VHDL PATH ip/i_syncbuf_n_sync_buffer_average_value37.vhd
add_fileset_file bb_average_value_B3.vhd VHDL PATH ip/bb_average_value_B3.vhd
add_fileset_file average_value_B3_branch.vhd VHDL PATH ip/average_value_B3_branch.vhd
add_fileset_file average_value_B3_merge.vhd VHDL PATH ip/average_value_B3_merge.vhd
add_fileset_file bb_average_value_B3_stall_region.vhd VHDL PATH ip/bb_average_value_B3_stall_region.vhd
add_fileset_file i_sfc_c0_for_cond_for_end_crit_edge_loopA0Z16_average_value.vhd VHDL PATH ip/i_sfc_c0_for_cond_for_end_crit_edge_loopA0Z16_average_value.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zaverage_value133.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zaverage_value133.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zlue139_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zlue139_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zue_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond_for_end_crit_A0Zue_full_detector.vhd
add_fileset_file i_sfc_logic_c0_for_cond_for_end_crit_edgA0Z_average_value67.vhd VHDL PATH ip/i_sfc_logic_c0_for_cond_for_end_crit_edgA0Z_average_value67.vhd
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA0Z463a0054c2a6355y.vhd VHDL PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA0Z463a0054c2a6355y.vhd
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA0Z0j0ucqp00j0oqf0z.vhd VHDL PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA0Z0j0ucqp00j0oqf0z.vhd
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA0ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA0ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA1ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA1ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA2ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA2ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA3ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA3ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA4ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA4ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA5ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA5ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA6ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA6ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA7ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA7ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA8ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA8ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA9ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA9ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA10ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA10ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA11ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA11ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA12ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA12ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA13ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA13ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA14ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA14ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA15ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA15ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA16ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA16ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA17ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA17ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA18ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA18ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA19ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA19ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA20ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA20ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA21ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA21ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA22ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA22ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA23ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA23ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA24ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA24ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA25ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA25ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA26ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA26ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA27ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA27ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA28ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA28ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA29ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA29ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA30ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA30ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA31ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA31ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA32ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA32ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA33ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA33ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA34ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA34ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA35ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA35ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA36ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA36ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA37ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA37ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA38ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA38ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA39ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA39ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA40ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA40ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA41ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA41ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA42ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA42ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA43ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA43ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA44ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA44ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA45ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA45ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA46ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA46ZinvTables_lutmem.hex
add_fileset_file floatComponent_i_sfc_logic_c0_for_cond_fA47ZinvTables_lutmem.hex HEX PATH ip/floatComponent_i_sfc_logic_c0_for_cond_fA47ZinvTables_lutmem.hex
add_fileset_file i_ffwd_dst_conv_i_i_i_i6_average_value71.vhd VHDL PATH ip/i_ffwd_dst_conv_i_i_i_i6_average_value71.vhd
add_fileset_file i_ffwd_dst_temp_0_0_0385_average_value69.vhd VHDL PATH ip/i_ffwd_dst_temp_0_0_0385_average_value69.vhd
add_fileset_file i_syncbuf_n_sync_buffer2_average_value73.vhd VHDL PATH ip/i_syncbuf_n_sync_buffer2_average_value73.vhd
add_fileset_file i_syncbuf_n_sync_buffer3_average_value116.vhd VHDL PATH ip/i_syncbuf_n_sync_buffer3_average_value116.vhd
add_fileset_file i_acl_push_i1_throttle_push_average_value135.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_average_value135.vhd
add_fileset_file i_acl_push_i1_throttle_push_average_value_reg.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_average_value_reg.vhd
add_fileset_file i_iowr_nb_return_unnamed_average_value8_A0Zaverage_value134.vhd VHDL PATH ip/i_iowr_nb_return_unnamed_average_value8_A0Zaverage_value134.vhd
add_fileset_file i_acl_pipeline_keep_going9_average_value_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_average_value_sr.vhd
add_fileset_file i_acl_pipeline_keep_going9_average_value_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_average_value_valid_fifo.vhd
add_fileset_file i_acl_pipeline_keep_going_average_value_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going_average_value_sr.vhd
add_fileset_file i_acl_pipeline_keep_going_average_value_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going_average_value_valid_fifo.vhd
add_fileset_file loop_limiter_average_value0.vhd VHDL PATH ip/loop_limiter_average_value0.vhd
add_fileset_file acl_avm_to_ic.v SYSTEM_VERILOG PATH ip/acl_avm_to_ic.v
add_fileset_file acl_mem1x.v SYSTEM_VERILOG PATH ip/acl_mem1x.v
add_fileset_file acl_mem_staging_reg.v SYSTEM_VERILOG PATH ip/acl_mem_staging_reg.v
add_fileset_file acl_ic_local_mem_router.v SYSTEM_VERILOG PATH ip/acl_ic_local_mem_router.v
add_fileset_file acl_ic_master_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_master_endpoint.v
add_fileset_file acl_arb_intf.v SYSTEM_VERILOG PATH ip/acl_arb_intf.v
add_fileset_file acl_ic_intf.v SYSTEM_VERILOG PATH ip/acl_ic_intf.v
add_fileset_file acl_ic_slave_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_slave_endpoint.v
add_fileset_file acl_ic_slave_rrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_rrp.v
add_fileset_file acl_ic_slave_wrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_wrp.v
add_fileset_file average_value_internal.v SYSTEM_VERILOG PATH average_value_internal.v

#### Primary clock for the component
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_assignment clock hls.cosim.name {$clock}
add_interface_port clock clock clk input 1

#### Primary reset for the component
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_assignment reset hls.cosim.name {$reset}
add_interface_port reset resetn reset_n input 1

#### The component slave protocol interrupt request interface (done_irq)
add_interface irq interrupt end
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset
set_interface_property irq associatedAddressablePoint avs_cra
set_interface_assignment irq hls.cosim.name {$irq}
add_interface_port irq done_irq irq output 1

#### Slave interface avs_a
add_interface avs_a avalon end
set_interface_property avs_a ENABLED true
set_interface_property avs_a associatedClock clock
set_interface_property avs_a associatedReset reset
set_interface_property avs_a addressAlignment DYNAMIC
set_interface_property avs_a burstOnBurstBoundariesOnly false
set_interface_property avs_a explicitAddressSpan 0
set_interface_property avs_a holdTime 0
set_interface_property avs_a isMemoryDevice false
set_interface_property avs_a isNonVolatileStorage false
set_interface_property avs_a linewrapBursts false
set_interface_property avs_a maximumPendingReadTransactions 0
set_interface_property avs_a printableDevice false
set_interface_property avs_a readLatency 3
set_interface_property avs_a readWaitTime 0
set_interface_property avs_a setupTime 0
set_interface_property avs_a timingUnits Cycles
set_interface_property avs_a writeWaitTime 0
set_interface_assignment avs_a hls.cosim.name {a}
add_interface_port avs_a avs_a_read read input 1
add_interface_port avs_a avs_a_write write input 1
add_interface_port avs_a avs_a_address address input 6
add_interface_port avs_a avs_a_writedata writedata input 32
add_interface_port avs_a avs_a_byteenable byteenable input 4
add_interface_port avs_a avs_a_readdata readdata output 32

#### Slave interface avs_cra
add_interface avs_cra avalon end
set_interface_property avs_cra ENABLED true
set_interface_property avs_cra associatedClock clock
set_interface_property avs_cra associatedReset reset
set_interface_property avs_cra addressAlignment DYNAMIC
set_interface_property avs_cra burstOnBurstBoundariesOnly false
set_interface_property avs_cra explicitAddressSpan 0
set_interface_property avs_cra holdTime 0
set_interface_property avs_cra isMemoryDevice false
set_interface_property avs_cra isNonVolatileStorage false
set_interface_property avs_cra linewrapBursts false
set_interface_property avs_cra maximumPendingReadTransactions 0
set_interface_property avs_cra printableDevice false
set_interface_property avs_cra readLatency 1
set_interface_property avs_cra readWaitTime 0
set_interface_property avs_cra setupTime 0
set_interface_property avs_cra timingUnits Cycles
set_interface_property avs_cra writeWaitTime 0
set_interface_assignment avs_cra hls.cosim.name {$cra}
add_interface_port avs_cra avs_cra_read read input 1
add_interface_port avs_cra avs_cra_write write input 1
add_interface_port avs_cra avs_cra_address address input 3
add_interface_port avs_cra avs_cra_writedata writedata input 64
add_interface_port avs_cra avs_cra_byteenable byteenable input 8
add_interface_port avs_cra avs_cra_readdata readdata output 64

#### Quartus settings (QIP strings)
set_qip_strings { "set_instance_assignment -entity \"%entityName%\" -library \"%libraryName%\" -name AUTO_SHIFT_REGISTER_RECOGNITION OFF -to *_NO_SHIFT_REG*"  }
